import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

export const metadata = {
  title: 'Terms of Use | SmallClaimsHelper',
  description: 'Terms of use for SmallClaimsHelper.com',
}

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <div className="container-narrow" style={{ paddingTop: '3rem', paddingBottom: '5rem' }}>
        <h1 style={{ marginBottom: '2rem' }}>Terms of Use</h1>
        {[
          { h: 'Not legal advice', p: 'SmallClaimsHelper.com is an automated document preparation service. We are not a law firm. Nothing on this website constitutes legal advice. We strongly recommend consulting a licensed attorney if you have questions about your specific situation.' },
          { h: 'No guarantee of outcome', p: 'Using this service does not guarantee any outcome in court. Court results depend on the specific facts of your case, applicable law, the judge, and many other factors outside our control.' },
          { h: 'Accuracy of information', p: 'We make every effort to keep state-specific information accurate and up to date. However, court rules, filing fees, and dollar limits can change. Always verify current requirements with your local court clerk before filing.' },
          { h: 'Use of generated documents', p: 'Documents generated by this service are templates to help you get started. You are responsible for reviewing and verifying all information before filing with a court.' },
          { h: 'Limitation of liability', p: 'SmallClaimsHelper shall not be liable for any damages arising from your use of this service, including but not limited to lost case outcomes, filing errors, or reliance on outdated information.' },
          { h: 'Changes to terms', p: 'We reserve the right to update these terms at any time. Continued use of the site constitutes acceptance of the updated terms.' },
        ].map(s => (
          <div key={s.h} style={{ marginBottom: '2rem' }}>
            <h2 style={{ fontSize: '1.15rem', marginBottom: '0.5rem' }}>{s.h}</h2>
            <p style={{ color: 'var(--gray-600)', lineHeight: 1.8 }}>{s.p}</p>
          </div>
        ))}
      </div>
      <Footer />
    </>
  )
}
