import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

export const metadata = {
  title: 'Legal Disclaimer | SmallClaimsHelper',
  description: 'Legal disclaimer for SmallClaimsHelper.com. This site is not a law firm and does not provide legal advice.',
}

export default function DisclaimerPage() {
  return (
    <>
      <Navbar />
      <div className="container-narrow" style={{ paddingTop: '3rem', paddingBottom: '5rem' }}>
        <h1 style={{ marginBottom: '2rem' }}>Legal Disclaimer</h1>
        {[
          { h: 'Not a law firm', p: 'SmallClaimsHelper.com is an automated document preparation service. We are NOT a law firm, and we do NOT provide legal advice. Use of this website does not create an attorney-client relationship.' },
          { h: 'No legal advice', p: 'The information provided on this website is for general informational purposes only. It is not intended to be, and should not be taken as, legal advice on any particular matter. Every legal situation is unique and the information here may not apply to your specific case.' },
          { h: 'Documents are templates only', p: 'All documents generated by SmallClaimsHelper are templates to help you get started. They are not guaranteed to be legally sufficient for your specific situation. You are solely responsible for reviewing, verifying, and completing all documents before filing them with any court.' },
          { h: 'Accuracy not guaranteed', p: 'We make every reasonable effort to keep court information, filing fees, and dollar limits accurate and current. However, laws and court rules change frequently. Always verify current requirements directly with your local court clerk before filing any documents.' },
          { h: 'Consult a licensed attorney', p: 'If you have any questions about your specific legal situation, we strongly recommend consulting a licensed attorney in your state. Many state bar associations offer free or low-cost legal referral services.' },
          { h: 'Limitation of liability', p: 'SmallClaimsHelper and its operators shall not be liable for any damages of any kind arising from your use of this website or the documents generated here, including but not limited to direct, indirect, incidental, punitive, and consequential damages.' },
        ].map(s => (
          <div key={s.h} style={{ marginBottom: '2rem', paddingBottom: '2rem', borderBottom: '1px solid var(--gray-100)' }}>
            <h2 style={{ fontSize: '1.15rem', marginBottom: '0.5rem' }}>{s.h}</h2>
            <p style={{ color: 'var(--gray-600)', lineHeight: 1.8 }}>{s.p}</p>
          </div>
        ))}
      </div>
      <Footer />
    </>
  )
}
